// <auto-generated />
using System;
using Blackjack.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blackjack.Model.Migrations
{
    [DbContext(typeof(BlackjackContext))]
    partial class BlackjackContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Blackjack.Model.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeckId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HandId")
                        .HasColumnType("uuid");

                    b.Property<int>("Suit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.HasIndex("HandId");

                    b.ToTable("Cards", (string)null);
                });

            modelBuilder.Entity("Blackjack.Model.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Decks", (string)null);
                });

            modelBuilder.Entity("Blackjack.Model.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CurrentRoundId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrentRoundId");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("Blackjack.Model.GameState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DealerHandId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerHandId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DealerHandId");

                    b.HasIndex("DeckId");

                    b.HasIndex("PlayerHandId");

                    b.ToTable("GameStates", (string)null);
                });

            modelBuilder.Entity("Blackjack.Model.Hand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Hands", (string)null);
                });

            modelBuilder.Entity("Blackjack.Model.Card", b =>
                {
                    b.HasOne("Blackjack.Model.Deck", null)
                        .WithMany("Cards")
                        .HasForeignKey("DeckId");

                    b.HasOne("Blackjack.Model.Hand", null)
                        .WithMany("Cards")
                        .HasForeignKey("HandId");
                });

            modelBuilder.Entity("Blackjack.Model.Game", b =>
                {
                    b.HasOne("Blackjack.Model.GameState", "CurrentRound")
                        .WithMany()
                        .HasForeignKey("CurrentRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentRound");
                });

            modelBuilder.Entity("Blackjack.Model.GameState", b =>
                {
                    b.HasOne("Blackjack.Model.Hand", "DealerHand")
                        .WithMany()
                        .HasForeignKey("DealerHandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blackjack.Model.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blackjack.Model.Hand", "PlayerHand")
                        .WithMany()
                        .HasForeignKey("PlayerHandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DealerHand");

                    b.Navigation("Deck");

                    b.Navigation("PlayerHand");
                });

            modelBuilder.Entity("Blackjack.Model.Deck", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Blackjack.Model.Hand", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
