name: deploy-blackjack-environments
concurrency: ola-blackjack

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  
  # lint the bicep file
  lint:
    uses: ./.github/workflows/lint.yml

  # deploy infrastructure to the test environment
  deploy-infrastructure-test:
    uses: ./.github/workflows/deploy-infrastructure.yml
    needs: lint
    with:
      environmentType: Test
      resourceGroupName: rg-ola-blackjack-test
      databaseAdministratorLogin: blackjackadmin
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_TEST }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      databaseAdministratorPassword: ${{ secrets.databaseAdministratorPassword }}

  # deploy infrastructure to the production environment
  deploy-infrastructure-production:
    uses: ./.github/workflows/deploy-infrastructure.yml
    needs: build-test
    with:
      environmentType: Production
      resourceGroupName: rg-ola-blackjack-Production
      databaseAdministratorLogin: blackjackadmin
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_PRODUCTION }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      databaseAdministratorPassword: ${{ secrets.databaseAdministratorPassword }}

  # build & deploy app to the test environment
  build-test:
    uses: ./.github/workflows/build-and-deploy-code.yml
    needs: deploy-infrastructure-test
    with:
      environmentType: Test
    secrets:
      POSTGRESQLCONNSTR_: ${{ secrets.POSTGRESQLCONNSTR_ }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_TEST }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  # build & deploy app to the production environment
  build-production:
    uses: ./.github/workflows/build-and-deploy-code.yml
    needs: deploy-infrastructure-production
    with:
      environmentType: Production
    secrets:
      POSTGRESQLCONNSTR_: ${{ secrets.POSTGRESQLCONNSTR_ }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_PRODUCTION }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
